### ISSUE TITLE
Logbook text seems to be misplaced; Is accidentally the logbook pickup name instead of the "lore"

### ISSUE THREAD

**Issue by HyperInvox** [viliger2/RoR2_EnemiesReturns#1]
![Risk_of_Rain_2_rDMK1IeMMm](https://github.com/user-attachments/assets/f124d039-48e2-4eb7-9783-0239e22a1939)
![Risk_of_Rain_2_gjzDSux67a](https://github.com/user-attachments/assets/07519681-3f0c-4bd3-8bb6-e33a9403cbe0)

title says all. gave me a chuckle when i first saw it.

**Comment by viliger2** [comment]
Fixed with 0.0.12
