### ISSUE TITLE
Mod's boss items don't get transformed into zoea

### ISSUE THREAD

**Issue by LordVGames** [viliger2/RoR2_EnemiesReturns#14]
i only noticed it with the ifrit boss item but this probably also applies to the colossus' boss item

![image](https://github.com/user-attachments/assets/f8be369f-7707-45c6-b8ec-7e407e2f6d23)

**Comment by viliger2** [comment]
With https://github.com/viliger2/RoR2_EnemiesReturns/commit/c3b09dc87f8031c4df0c0b5a88b7828a68379a63 I've implemented our own ItemRelationshipProvider so all current and future boss items will get turned into Newly Hatched Zoea.
