### ISSUE TITLE
Add config option to disable the colossus' boss item

### ISSUE THREAD

**Issue by LordVGames** [viliger2/RoR2_EnemiesReturns#6]
i wanna disable the item since i've configured the colossus to never spawn, but the colossal fist only has options for the stats and no option to disable it. i'd rather not get contentdisabler just to keep the colossal fist from spawning so if there could be an option to disable the item that would be great

**Comment by viliger2** [comment]
With 62d764723b94d5460c45f44045baecc220a95881 you can now disable enemies and their items, they can be disabled separately from each other, meaning without the boss items will still be in the game, but only obtainable via printers or command artifact.
