### ISSUE TITLE
Ifrit death state NRE

### ISSUE THREAD

**Issue by Phreelosu** [viliger2/RoR2_EnemiesReturns#9]
[LogOutput.log](https://github.com/user-attachments/files/17482103/LogOutput.log)

yea this is pretty long into the run but I think its worth to mention that if an Ifrit is destroyed by lost seer's lenses the death state throws an NRE every frame

**Comment by viliger2** [comment]
Should be fixed with ab6c6b09ff6e2d6b0463d43f071a0e62b27175bc
